name: Release Data

on:
  push:
    branches: ["master"]

jobs:
  test:
    uses: ProjectTorreyPines/GitHubActionsWorkflows/.github/workflows/artifact_release.yml@artifact_release_workflow
    secrets: inherit
    with:
      data_path: "data"