name: Release Regression Data

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Set version (based on date or commit)
        run: echo "RELEASE_TAG=v$(date +'%Y.%m.%d')-$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Create archive (excluding README and LICENSE)
        run: |
          mkdir dist
          # Create a clean directory structure for the tar
          mkdir temp_archive
          cp -r . temp_archive/
          cd temp_archive
          rm -f README.md LICENSE .git* .github*
          # Normalize permissions and create reproducible tar
          find . -type f -exec chmod 644 {} \;
          find . -type d -exec chmod 755 {} \;
          # Create tar with normalized timestamps
          tar --sort=name --owner=0 --group=0 --numeric-owner --mtime='2000-01-01' -czf ../dist/data.tar.gz *
          cd ..
          rm -rf temp_archive

      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.10'

      - name: Compute hashes
        run: |
          # Install required Julia packages
          julia -e 'using Pkg; Pkg.add(["Tar", "CodecZlib", "SHA"])'
          
          # Compute both hashes with debugging
          julia -e '
          using Tar, CodecZlib, SHA
          
          # Read the tarball
          tarball_data = read("dist/data.tar.gz")
          
          # Compute SHA256 of the tarball itself
          tarball_sha = bytes2hex(sha256(tarball_data))
          
          # Decompress and compute git-tree-sha1 of contents
          decompressed = transcode(GzipDecompressor, tarball_data)
          
          # Debug: Check what files are in the tar
          println("Files in tarball:")
          Tar.list(IOBuffer(decompressed)) do hdr
              println("  $(hdr.path) (type: $(hdr.type), size: $(hdr.size))")
          end
          
          # Compute tree hash
          tree_sha = Tar.tree_hash(IOBuffer(decompressed))
          
          # Alternative method for comparison (using artifact_hash from Pkg)
          using Pkg.Artifacts
          temp_dir = mktempdir()
          try
              Tar.extract(IOBuffer(decompressed), temp_dir)
              alt_tree_sha = Pkg.Artifacts.artifact_hash(temp_dir)
              println("Tar.tree_hash result: $tree_sha")
              println("Pkg.Artifacts.artifact_hash result: $alt_tree_sha")
              
              # Use the Pkg.Artifacts version as it matches what Julia expects
              final_tree_sha = alt_tree_sha
          finally
              rm(temp_dir, recursive=true)
          end
          
          # Create the artifact info in TOML format
          artifact_toml = """
          [data]
          git-tree-sha1 = "$final_tree_sha"
          
          [[data.download]]
          url = "https://github.com/${{ github.repository }}/releases/download/${{ env.RELEASE_TAG }}/data.tar.gz"
          sha256 = "$tarball_sha"
          """
          
          write("dist/Artifacts.toml", artifact_toml)
          
          # Also create a simple hash info file for reference
          hash_info = """
          Tarball SHA256: $tarball_sha
          Git-tree SHA1: $final_tree_sha
          Tar.tree_hash: $tree_sha
          Pkg.Artifacts.artifact_hash: $alt_tree_sha
          Release: ${{ env.RELEASE_TAG }}
          """
          
          write("dist/hash-info.txt", hash_info)
          '

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          name: "Automated release ${{ env.RELEASE_TAG }}"
          files: |
            dist/data.tar.gz
            dist/Artifacts.toml
            dist/hash-info.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Output hashes for reference
        run: |
          echo "Generated Artifacts.toml:"
          cat dist/Artifacts.toml
          echo ""
          echo "Hash information:"
          cat dist/hash-info.txt