name: Release Regression Data

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      

      - name: Set version (based on date or commit)
        run: echo "RELEASE_TAG=v$(date +'%Y.%m.%d')-$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Create archive (excluding README and LICENSE)
        run: |
          mkdir dist
          tar --exclude='README.md' --exclude='LICENSE' -czf dist/data.tar.gz .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          name: "Automated release ${{ env.RELEASE_TAG }}"
          files: dist/data.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  compute-hash:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.10'

      - name: Download release archive
        run: curl -L -o data.tar.gz https://github.com/YOURUSER/sample-data/releases/download/latest/data.tar.gz

      - name: Compute git-tree-sha1
        run: |
          julia --project -e <<EOF
            using Pkg
            Pkg.add(["Tar", "Inflate", "SHA"])
            using Tar, Inflate, SHA

            filename = "data.tar.gz"
            sha = "sha256: "* bytes2hex(open(sha256, filename)))
            git-tree-sha = "git-tree-sha1: "* Tar.tree_hash(IOBuffer(inflate_gzip(filename)))
            write("artifact-info.toml", "[data]\n $sha\ngit-tree-sha\n")
          EOF

      - name: Upload artifact-info
        uses: softprops/action-gh-release@v1
        with:
          files: artifact-info.toml